# Generated by Django 4.2.7 on 2024-09-29 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 8, 48, 11, 599266, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
