# Generated by Django 4.2.7 on 2024-10-15 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_mission_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 14, 21, 18, 205457, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
